name: Django CI

on:
  pull_request:
    branches: [ main ] # Adjust branch names as necessary

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Specify your required Python version (e.g., '3.10')

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Assumes you have a requirements.txt file

    - name: Run Tests
      # Set Django settings module environment variable
      # env:
      #   DJANGO_SETTINGS_MODULE: your_project_name.settings # Replace with your project's settings module
      run: |
        python manage.py test
